name: Example Workflow

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  pre-auth:
    runs-on: ubuntu-latest
    outputs:
      docker_auth_token: ${{ steps.auth.outputs.docker_auth_token }}

    steps:
      - name: Authenticate to Container Registry
        id: auth
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: pre-auth
    name: Test the Action
    runs-on: ubuntu-latest

    steps:
      - name: Run the Container Action
        id: run
        uses: sergei-tol/test-gh-action@v0.1.1
        with:
          who-to-greet: Mona Lisa Octocat

      - name: Print Output
        id: output
        run: echo "${{ steps.run.outputs.greeting }}"
